// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.4
// source: rpc/chord.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Empty) Reset() {
	*x = Empty{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chord_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chord_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_rpc_chord_proto_rawDescGZIP(), []int{0}
}

type HashFuncResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HashVal string `protobuf:"bytes,1,opt,name=HashVal,proto3" json:"HashVal,omitempty"`
}

func (x *HashFuncResponse) Reset() {
	*x = HashFuncResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_chord_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HashFuncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HashFuncResponse) ProtoMessage() {}

func (x *HashFuncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_chord_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HashFuncResponse.ProtoReflect.Descriptor instead.
func (*HashFuncResponse) Descriptor() ([]byte, []int) {
	return file_rpc_chord_proto_rawDescGZIP(), []int{1}
}

func (x *HashFuncResponse) GetHashVal() string {
	if x != nil {
		return x.HashVal
	}
	return ""
}

var File_rpc_chord_proto protoreflect.FileDescriptor

var file_rpc_chord_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x70, 0x63, 0x2f, 0x63, 0x68, 0x6f, 0x72, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x07, 0x0a, 0x05, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x2c,
	0x0a, 0x10, 0x48, 0x61, 0x73, 0x68, 0x46, 0x75, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x48, 0x61, 0x73, 0x68, 0x56, 0x61, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x48, 0x61, 0x73, 0x68, 0x56, 0x61, 0x6c, 0x32, 0x3f, 0x0a, 0x05,
	0x43, 0x68, 0x6f, 0x72, 0x64, 0x12, 0x36, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x48, 0x61, 0x73, 0x68,
	0x46, 0x75, 0x6e, 0x63, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x75, 0x6d, 0x12, 0x09, 0x2e, 0x70,
	0x62, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x14, 0x2e, 0x70, 0x62, 0x2e, 0x48, 0x61, 0x73,
	0x68, 0x46, 0x75, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x19, 0x5a,
	0x17, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x2d, 0x63,
	0x68, 0x6f, 0x72, 0x64, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_chord_proto_rawDescOnce sync.Once
	file_rpc_chord_proto_rawDescData = file_rpc_chord_proto_rawDesc
)

func file_rpc_chord_proto_rawDescGZIP() []byte {
	file_rpc_chord_proto_rawDescOnce.Do(func() {
		file_rpc_chord_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_chord_proto_rawDescData)
	})
	return file_rpc_chord_proto_rawDescData
}

var file_rpc_chord_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_chord_proto_goTypes = []interface{}{
	(*Empty)(nil),            // 0: pb.Empty
	(*HashFuncResponse)(nil), // 1: pb.HashFuncResponse
}
var file_rpc_chord_proto_depIdxs = []int32{
	0, // 0: pb.Chord.GetHashFuncCheckSum:input_type -> pb.Empty
	1, // 1: pb.Chord.GetHashFuncCheckSum:output_type -> pb.HashFuncResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_chord_proto_init() }
func file_rpc_chord_proto_init() {
	if File_rpc_chord_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_chord_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Empty); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_chord_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HashFuncResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_chord_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rpc_chord_proto_goTypes,
		DependencyIndexes: file_rpc_chord_proto_depIdxs,
		MessageInfos:      file_rpc_chord_proto_msgTypes,
	}.Build()
	File_rpc_chord_proto = out.File
	file_rpc_chord_proto_rawDesc = nil
	file_rpc_chord_proto_goTypes = nil
	file_rpc_chord_proto_depIdxs = nil
}
